name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Run the workflow on pull requests to the main branch

jobs:
  pipeline:
    runs-on: windows-latest  # Use a Windows runner

    env:
      VENV: venv
      REQUIREMENTS_FILE: requirements.txt
      LINT_REPORT_DIR: lint_reports
      MODEL_SCRIPT: housingdatamodel.py

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the required Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m venv ${{ env.VENV }}
        ${{ env.VENV }}\Scripts\activate
        pip install --upgrade pip
        pip install -r ${{ env.REQUIREMENTS_FILE }}
        pip install flake8 flake8-html pytest

    # Step 4: Run linting
    - name: Run linting
      run: |
        ${{ env.VENV }}\Scripts\activate
        mkdir ${{ env.LINT_REPORT_DIR }}
        flake8 --max-line-length=120 --format=html --htmldir=${{ env.LINT_REPORT_DIR }} .
      continue-on-error: true  # Allow the pipeline to continue even if linting fails

    # Step 5: Run tests
    - name: Run tests
      run: |
        ${{ env.VENV }}\Scripts\activate
        pytest --disable-warnings --junitxml=test-results.xml

    # Step 6: Deploy the ML model
    - name: Deploy ML Model
      run: |
        ${{ env.VENV }}\Scripts\activate
        python ${{ env.MODEL_SCRIPT }}

    # Step 7: Upload linting and test results as artifacts
    - name: Upload Linting Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: lint-report
        path: ${{ env.LINT_REPORT_DIR }}

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.xml
